import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <nav></nav>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
