create table node_type (
  name text primary key,
  icon text,
  top_level boolean default false
);
alter table node_type enable row level security;
create policy "Anyone can read node types" on node_type
  for select using (true);
create policy "Admin can manage node types" on node_type
  for all using (is_admin());

create table node (
  id bigint primary key generated by default as identity,
  type text not null,
  user_id uuid references auth.users(id) not null,
  data jsonb,
  public boolean default false
);
alter table node enable row level security;
create policy "Anyone can read nodes that are public" on node
  for select using (public = true);
create policy "Authenticated user can manage their nodes" on node
  for all using (auth.uid() = user_id);

create table edge (
  source bigint references node(id) not null,
  destination bigint references node(id) not null,
  user_id uuid references auth.users(id) not null,
  data jsonb,
  public boolean default false
);
alter table edge enable row level security;
create policy "Anyone can read edges that are public" on edge
  for select using (public = true);
create policy "Authenticated user can manage their edges" on edge
  for all using (auth.uid() = user_id);
