create table step (
  id bigint primary key generated by default as identity,
  description text not null,
  bucket text not null,
  object_name text not null,
  user_id uuid references auth.users(id) not null
);
alter table step enable row level security;
create policy "Authenticated user can manage their steps" on step
  for all using (auth.uid() = user_id);
